version: "3.2"
services:
  python:
    build: 
      context: './python/'
    links:
      - "mysql:db"
    ports:
      - "5000:5000"
    volumes:
      - python:/app
    container_name: python
  mysql:
    build:
      context: './mysql/'
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
#      - mysql/custom:/etc/mysql/conf.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    container_name: mysql
volumes:
  python:
  mysql:
