FROM mariadb:10.3-bionic
#RUN ["/bin/bash", "-c", "sleep 10"]
#CMD ["mysql", "-uroot","-e", "CREATE DATABASE flasktest; GRANT ALL ON flasktest.* TO flaskuser@localhost IDENTIFIED BY 'flask123'; FLUSH PRIVILEGES;"]
#CMD ["sleep", "30", "mysql", "-uroot", "-e", "CREATE DATABASE flasktest; GRANT ALL ON flasktest.* TO flaskuser@localhost IDENTIFIED BY 'flask123'; FLUSH PRIVILEGES;" ]
#CMD sleep 30
