FROM mariadb:10.3-bionic
COPY ./docker-entrypoint-initdb.d /docker-entrypoint-initdb.d
#RUN []
#CMD ["mysql", "-uroot","-e", "CREATE DATABASE flasktest; GRANT ALL ON flasktest.* TO flaskuser@localhost IDENTIFIED BY 'flask123'; FLUSH PRIVILEGES;"]
#CMD ["sleep", "30", "mysql", "-uroot", "-e", "CREATE DATABASE flasktest; GRANT ALL ON flasktest.* TO flaskuser@localhost IDENTIFIED BY 'flask123'; FLUSH PRIVILEGES;" ]
#CMD sleep 30
